name: Commit
on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    name: Build docker image
    steps:
      - uses: actions/checkout@master

      - name: GitHub Package Registry
        uses: aevea/action-kaniko@master
        with:
          registry: ghcr.io
          password: ${{ secrets.GITHUB_TOKEN }}
          image: kaniko
          cache: true
          cache_registry: cache

      - name: Dockerhub
        uses: aevea/action-kaniko@master
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          image: aevea/kaniko
          cache: true
          cache_registry: aevea/cache
